name: main
on: push

jobs:
  makeNames:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.names.outputs.names }}
    steps:
      - name: Checkout Ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #ref: ${{ inputs.tag }}

      - name: Restore Cached Files
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.npm
            ./.cache
            ./tools/node_modules
          key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
          restore-keys: ${{ runner.os }}-bunny-

      - name: Setup NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Setup NPM Packages
        working-directory: ./tools
        run: npm ci
        
      - name: Make Names
        working-directory: ./tools
        id: name
        run: npx gulp makeGHANames
 
  printNames:
    runs-on: ubuntu-latest
    needs: makeNames
    strategy:
      matrix: 
        include: ${{ fromJson(needs.makeNames.outputs.names) }}
    steps:
      - run: |
          echo ${{ matrix.FILENAME }}
    